### ISSUE TITLE
Compiler error (Type conflict)

### ISSUE THREAD

**Issue by ParzivalWolfram** [uyjulian/pfsshell#4] opened 2019-03-07 21:01 UTC
```
death@euclidean-spice:~/pfsshell$ make
-e 	CC  startup.c
-e 	CC  hl.c
-e 	CC  util.c
-e 	CC  shell.c
make -C fake_sdk
make[1]: Entering directory '/home/death/pfsshell/fake_sdk'
-e 	CC  atad.c
ar rcs libfakeps2sdk.a atad.o
make[1]: Leaving directory '/home/death/pfsshell/fake_sdk'
make -C iomanX
make[1]: Entering directory '/home/death/pfsshell/iomanX'
-e 	CC  iomanX.c
iomanX.c: In function ‘AddDrv’:
iomanX.c:77:9: warning: unused variable ‘oldIntr’ [-Wunused-variable]
     int oldIntr;
         ^~~~~~~
iomanX.c: In function ‘get_new_file’:
iomanX.c:181:9: warning: unused variable ‘oldIntr’ [-Wunused-variable]
     int oldIntr;
         ^~~~~~~
In file included from iomanX.c:20:0:
iomanX.c: At top level:
../fake_sdk/include/iomanX.h:113:17: error: conflicting types for ‘iomanx_lseek64’
 #define lseek64 iomanx_lseek64
                 ^
iomanX.c:570:11: note: in expansion of macro ‘lseek64’
 long long lseek64(int fd, long long offset, int whence)
           ^~~~~~~
../fake_sdk/include/iomanX.h:113:17: note: previous declaration of ‘iomanx_lseek64’ was here
 #define lseek64 iomanx_lseek64
                 ^
../fake_sdk/include/iomanX.h:184:5: note: in expansion of macro ‘lseek64’
 s64 lseek64(int fd, s64 offset, int whence);
     ^~~~~~~
../Defs.mak:15: recipe for target 'iomanX.o' failed
make[1]: *** [iomanX.o] Error 1
make[1]: Leaving directory '/home/death/pfsshell/iomanX'
Makefile:40: recipe for target 'iomanX/libiomanX.a' failed
make: *** [iomanX/libiomanX.a] Error 2
```
Seems to be a code issue.

**Comment by uyjulian** [comment] 2019-03-07 22:33
Duplicate of #3

**Closed as completed by uyjulian** 2019-03-07 22:33 UTC
